# Built with Jekyll 3.2.0

# Setup
title:               Palladio
tagline:             'Visualize complex historical data with ease.'
description:         'Palladio is developed at Humanities + Design, Stanford University.'
url:                 'http://hdlab.stanford.edu/palladio'
urlimg: 'http://localhost:4000/assets/'
baseurl:             ''

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  tutorials:
    output: true
  releasenotes:
    output: true
  testimonials:
    output: true
    

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             1.1.4

# Exclusions from the final site
exclude: [optional, vendor]


